project_id = "vkbummbomljtgnmexkfp"

[functions.send-order-email]
verify_jwt = false

[functions.notify-admin-payment]
verify_jwt = false

[functions.notify-signup]
verify_jwt = false

[functions.notify-order]
verify_jwt = false