// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function db() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search Trendra's product catalog by keywords, with optional min/max price (INR). Returns up to 10 active products.",
  inputSchema: {
    query: z.string().describe("Free-text search across name and description, e.g. 'red kurta'"),
    minPrice: z.number().optional().describe("Minimum price in INR"),
    maxPrice: z.number().optional().describe("Maximum price in INR")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, minPrice, maxPrice }) => {
    let q = db().from("products").select("id,name,slug,price,mrp,discount_percent,images,description,stock").eq("is_active", true).limit(10);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (typeof minPrice === "number") q = q.gte("price", minPrice);
    if (typeof maxPrice === "number") q = q.lte("price", maxPrice);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details of a single product by its slug or id.",
  inputSchema: {
    slugOrId: z2.string().describe("Product slug (preferred) or UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slugOrId }) => {
    const client = db2();
    const isUuid = /^[0-9a-f-]{36}$/i.test(slugOrId);
    const { data, error } = await client.from("products").select("*").eq(isUuid ? "id" : "slug", slugOrId).eq("is_active", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function db3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all product categories available on Trendra.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await db3().from("categories").select("id,name,slug,image_url").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "trendra-mcp",
  title: "Trendra Shop",
  version: "0.1.0",
  instructions: "Trendra is an Indian e-commerce store. Use `search_products` to find items by keywords and optional price range, `get_product` for full details of a specific product, and `list_categories` to browse the catalog structure. Product links follow /product/<slug>.",
  tools: [search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
